name: teaseme_flutter
description: A sassy TeaseMe frontend
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  flutter_animate: ^4.5.0
  flutter_spinkit: ^5.2.0
  shared_preferences: ^2.2.2
  flutter_stripe: ^10.0.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/teaser_bg.jpg
    - assets/images/sensual_pattern.png
    - assets/images/tsm_1.jpeg
    - assets/images/tsm_2.jpeg
    - assets/images/tsm_3.jpeg
    - assets/images/tsm_4.jpeg
    - assets/images/tsm_5.jpeg
    - assets/fonts/